task/DES-2562: Add My Data (Work) to listings
DesignSafe-CI/portal pull request #1082
Opened 2023-08-03 18:17 UTC by jarosenb

## Overview: ##
Add My Data (Work) as a nav option in the Data Depot and Workspace.

## PR Status: ##

* [X] Ready.
* [ ] Work in Progress.
* [ ] Hold.

## Related Jira tickets: ##

* [DES-2562](https://jira.tacc.utexas.edu/browse/DES-2562)

## Summary of Changes: ##

## Testing Steps: ##
1. Navigate to My Data (Work) in the Data Depot
2. in the Workspace, select My Data (Work) from the file browser.

## UI Photos:
<img width="1672" alt="image" src="https://github.com/DesignSafe-CI/portal/assets/12601812/a3aa5596-aaa2-47c4-8a34-1b61f9c15bc1">
<img width="1222" alt="image" src="https://github.com/DesignSafe-CI/portal/assets/12601812/47bfd0b3-d724-4c05-8522-b3491f22d4cc">

## Notes: ##

2023-08-16 19:45 UTC, jarosenb commented
No longer needed, we are updated `desigsnafe.storage.default` directly.

2023-08-22 21:52 UTC, rstijerina requested changes
Updated for `designsafe.storage.frontera.scratch`

2023-08-22 21:52 UTC, rstijerina commented on designsafe/static/scripts/data-depot/components/data-depot-nav/data-depot-nav.component.js
> +          description: 'Working directory for use with JupyterHub'
```suggestion
          name: 'Scratch (Frontera)',
          collapsible: false,
          state: 'myDataScratch',
          description: 'Scratch directory on Frontera for use with JupyterHub'
```

2023-08-22 21:52 UTC, rstijerina commented on designsafe/static/scripts/data-depot/components/data-depot-toolbar/data-depot-toolbar.component.js
> +            'myDataWork': 'My Working Files',
```suggestion
            'myDataScratch': 'Scratch (Frontera)',
```

2023-08-22 21:52 UTC, rstijerina commented on designsafe/static/scripts/data-depot/index.js
> +                systemId: 'designsafe.storage.working',
```suggestion
        .state('myDataScratch', {
            url: '/agave/{systemId}/{filePath:any}/?query_string&offset&limit',
            component: 'dataDepotBrowser',
            params: {
                systemId: 'designsafe.storage.frontera.scratch',
```

2023-08-22 21:52 UTC, rstijerina commented on designsafe/static/scripts/ng-designsafe/services/file-operation-service.js
> +        const agaveDataStates = ['myData', 'myDataWork', 'projects.view', 'projects.curation'];
```suggestion
        const agaveDataStates = ['myData', 'myDataScratch', 'projects.view', 'projects.curation'];
```

2023-08-22 21:52 UTC, rstijerina commented on designsafe/static/scripts/workspace/components/workspace-data-browser/workspace-data-browser.component.js
> +            { name: 'myDataWork', label: 'My Working Files' },
```suggestion
            { name: 'myDataScratch', label: 'Scratch (Frontera)' },
```

2023-08-22 21:52 UTC, rstijerina commented on designsafe/static/scripts/workspace/components/workspace-data-browser/workspace-data-browser.component.js
> +                    system: 'designsafe.storage.working',
```suggestion
            case 'myDataScratch':
                this.listingType = 'files';
                this.FileListingService.browse({
                    section: 'main',
                    api: 'agave',
                    scheme: 'private',
                    system: 'designsafe.storage.frontera.scratch',
```

2023-08-23 15:47 UTC, merged