Task/wg 370 open topo UI improvements
DesignSafe-CI/portal pull request #1420
Opened 2024-08-26 23:37 UTC by sophia-massie

## Overview: ##

## PR Status: ##

* [ ] Ready.
* [X] Work in Progress.
* [ ] Hold.

## Related Jira tickets: ##

* [WG-370](https://tacc-main.atlassian.net/browse/WG-370)

## Summary of Changes: ##
Still a WIP

## Testing Steps: ##
1. Go to https://designsafe.dev/recon-portal/
2. Click 'Show filter options' above the map

## UI Photos:
![Screenshot 2024-08-26 at 6 34 09 PM](https://github.com/user-attachments/assets/806ae767-e8a8-492a-b93c-bc2d1aeea5be)

## Notes: ##

2024-08-28 21:29 UTC, nathanfranklin commented on .nx/cache/18.3.2-nx.darwin-x64.node
I see this nx file made its way in.  should we drop and then hotfix something to the .gitignore to ingore the .nx folder?

2024-08-28 21:42 UTC, nathanfranklin requested changes
LGTM. looks great! 

just one comment on the extra file.

2024-08-28 21:59 UTC, shayanaijaz approved these changes
LGTM!

2024-08-30 18:57 UTC, sophia-massie commented on .nx/cache/18.3.2-nx.darwin-x64.node
Ah sorry! This wasn't even registering locally as an added file. It's now removed

2024-08-30 19:15 UTC, nathanfranklin approved these changes
LGTM 👍

2024-08-30 19:33 UTC, merged