Task/DES-1286: Send user email immediately after clicking Request DOI & Publish
DesignSafe-CI/portal pull request #788
Opened 2020-08-26 21:08 UTC by owaisj

When the user clicks Request DOI & Publish, an additional task has been added to the publish chain that notifies the user that the project is being prepared for publication.
<img width="820" alt="Screen Shot 2020-08-26 at 4 06 01 PM" src="https://user-images.githubusercontent.com/47395902/91356938-11633580-e7b6-11ea-9ce8-28ab1bbd655f.png">

2020-08-28 21:46 UTC, fnets submitted a review, later dismissed
LGTM and works locally (at least the celery task does.)

2020-09-23 15:15 UTC, rstijerina requested changes

2020-09-23 15:15 UTC, rstijerina commented on designsafe/apps/api/tasks.py
> +    """.format(pub_url="https://www.designsafe-ci.org/data/browser/public/", ticket_url="https://www.designsafe-ci.org/help/new-ticket/")
Could you add something to the end to let them know not to reply to this message?

```
This is a programmatically generated message. Do NOT reply to this message. If you have any feedback or questions, please feel free to <a href=\"{ticket_url}\">please submit a ticket.</a>
```

2020-10-02 17:37 UTC, rstijerina requested changes

2020-10-02 17:37 UTC, rstijerina commented on designsafe/apps/api/tasks.py
> +    If you have any feedback or questions, please feel free to <a href=\"{ticket_url}\">please submit a ticket.</a></p>
```suggestion
    If you have any feedback or questions, please feel free to <a href=\"{ticket_url}\">submit a ticket.</a></p>
```

2020-10-02 18:08 UTC, rstijerina approved these changes

2020-10-02 18:08 UTC, merged